name: HeartPocket Stories
favicon: null
layout_spectrum: 0.00087
typography_spectrum: 0.12716
title: For the love you receive
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3a3b'
    - '#fbe1d4'
    - '#1f160d'
    - '#636469'
    - '#9e979e'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
